[package]
name = "chronicle"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
chronicle-capture.workspace = true
chronicle-core.workspace = true
chronicle-derive.workspace = true
chronicle-mcp.workspace = true
chronicle-server.workspace = true
clap.workspace = true
crossbeam-channel.workspace = true
eframe.workspace = true
jiff.workspace = true
regex.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[features]
metal = ["chronicle-derive/metal"]
vulkan = ["chronicle-derive/vulkan"]
